[package]
name = "lanremotecontrol-host"
version.workspace = true
edition.workspace = true
description = "Host service for LANRemoteControl - runs on the machine being controlled"

[dependencies]
lanremotecontrol-common = { path = "../common" }
serde.workspace = true
bincode.workspace = true
ctrlc = "3.5.2"
windows.workspace = true
windows-core.workspace = true
